### ISSUE TITLE
Errors on Archive 

### ISSUE THREAD

**Issue by gvardikos** [infinum/iOS-Loggie#33] opened 2022-12-21 13:15 UTC
Hello! 

First of all great library thanks for sharing! 
when trying to Archive the binary for TestFligh distribution, it has some build errors like the following 

<img width="1126" alt="Screenshot 2022-12-21 at 15 20 40" src="https://user-images.githubusercontent.com/13052073/208914894-b3de9dc4-e637-4b5d-bfcb-ea884624a190.png">

I suppose is something that the lib needs to address?

Thank you, guys!

**Comment by hhrvoic** [comment] 2023-01-05 09:57
Hi @gvardikos, thanks for sharing the problem. Can you provide more info about your project, like min deployment version (min iOS), Swift version, do you use SwiftUI/UIKit? 

It's not real solution to the problem, but for the starters I suggest to disable Loggie for the Appstore builds, not sure what is your use case for having it there? It's a tool made for the debugging purposes while in development, not something that a real user would look at.

For the real solution to the problem, we still have one PR waiting for the new release, so I would expect that PR resolves this issue (when we confirm the cause). 
cc @dimovskidamjan  @nikolamajcen

**Comment by gvardikos** [comment] 2023-01-05 14:54
Hi @hhrvoic, thanks for your response.  

The min iOS version is 15.0, the swift version is 5.0 and the project is using UIKit.

Thanks for your suggestion, the Loggie is enabled only for the dev environment distributed through the TestFlight in the QA.

**Comment by nikolamajcen** [comment] 2023-03-01 09:37
Hey @gvardikos , a new release `2.4.0` has been released. Can you check if that happens on that version as well?

I've tried to reproduce this by creating a new project and including `Loggie` inside. When I tried to create an archive, everything went well - I was using the configuration you mentioned; 

* iOS 15.0 (deployment target)
* Swift 5.0
* UIKit

**Comment by nikolamajcen** [comment] 2023-03-14 10:39
Hey @gvardikos, do you still have the same problem with the latest release of this library?

**Comment by gvardikos** [comment] 2023-03-16 09:19
Hi @nikolamajcen 
The issue exists in the 2.4.0

Furthermore, I created two empty projects - one with Storyboard and the other with SwiftUI - and both failed on the archive with the same error as the previous one. 
<img width="1136" alt="Screenshot 2023-03-16 at 11 21 11" src="https://user-images.githubusercontent.com/13052073/225571954-4470c6b8-8275-4b7f-95c2-99745f5dd15c.png">

**Comment by nikolamajcen** [comment] 2023-03-16 15:00
Hi, @gvardikos thank you for your feedback. 
Can you please upload the project for easier debugging?

You can upload a zip or create a new public repo and share it here.

When using the `2.4.0` version, please check the release notes;

> * to use Loggie with `URLSession`, install Loggie as `Loggie/URLSession`
> * to use Loggie with `Alamofire`, install Loggie as `Loggie/LoggieAlamofire`

Just using `pod 'Loggie'` for `2.4.0` won't work.
We update that in `2.4.1` and everything should work as expected ([release notes](https://github.com/infinum/iOS-Loggie/releases)).

**Comment by gvardikos** [comment] 2023-03-20 09:31
[loggieTest.zip](https://github.com/infinum/iOS-Loggie/files/11016155/loggieTest.zip)
Hi @nikolamajcen !
I am using the SPM version. Attaching the zip containing the test project.

**Comment by nikolamajcen** [comment] 2023-03-20 09:36
Hey @gvardikos , I've downloaded the provided zip file and tried to archive the project.
I was able to create an archive without any issues.

![loggie-archive](https://user-images.githubusercontent.com/11491550/226300752-1e09364d-a186-4fe6-b7a5-d8bb61bc940b.png)

**Comment by nikolamajcen** [comment] 2023-03-20 09:37
Which Xcode version did you use?  I've done this on the Xcode 14.2.

**Comment by gvardikos** [comment] 2023-03-20 09:39
I am using 13.4

**Comment by gvardikos** [comment] 2023-03-20 09:41
I tried the Xcode 14.0 RC1 and I did create the archive

**Comment by nikolamajcen** [comment] 2023-03-20 09:42
Okay, thanks for the input. Can you update the Xcode version? I think that will solve your issue.

I'll try downloading the Xcode 13.4 this week and see why this does not work.

**Comment by gvardikos** [comment] 2023-03-20 12:02
Thank you @nikolamajcen ! we will update in Xcode 14 in the next sprint.

Thanks again for the great library!

**Comment by nikolamajcen** [comment] 2023-03-21 08:15
Hey @gvardikos , I'm happy you're using our library and thankful for your feedback!

Also, about the reported issue - I've checked Xcode 13.4.1 and changing the minimum version to iOS 11 resolved the issue. But, unfortunately, I didn't have more time to dig a bit deeper.

Based on [Apple submission notes](https://developer.apple.com/ios/submit/), that says;

> Please note, starting April 2023, all iOS and iPadOS apps submitted to the App Store must be built with Xcode 14.1 and the iOS 16.1 SDK.

and [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-14_1-release-notes) for Xcode 14.1 that states:

> The Xcode 14 release supports on-device debugging in iOS 11 and later, tvOS 11 and later, and watchOS 4 and later. Xcode 14 requires a Mac running macOS Monterey 12.5 or later.

we will update the minimum iOS version of the package to iOS 11 in the next release, which will resolve this issue.

**Comment by nikolamajcen** [comment] 2023-04-11 14:21
Changes are merged to the `master` branch, and a new version will fix this issue. Based on that, I'm closing this issue.

**Closed as completed by nikolamajcen** 2023-04-11 14:21 UTC
Labels: bug
